### ISSUE TITLE
Database Query service always fails with QueryOptions

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.Hive.Node#152]
When calling the Database Query service with QueryOptions, the format of the `sort` attribute is not deserialized properly on the server. We tried using multiple formats:

sort:[{"key":"_id", "order": 1}]
sort:[{"key":"_id", "order": "asc"}]
sort:[{"_id":1}]
sort:[{"_id":"asc"}]

but the response is always a stack trace pointing to json.loads call of the the Database.__do_find method called by Database.query_document in src/modules/database/database.py, complaning about the `sort` property format of the QueryOptions.

Looking at the tests test06_query_document of tests/database_test.py, we can see that the expected `sort` format seems to use parenthesis : 

'sort': [('_id', 1)]

The problem with this format is that it's not JSON compliant. Because the request payload is first read as a JSON object, using this format automatically returns a JSON format error way before getting into the Database.query_document service method. The format must be JSON compliant.

**Comment by fred-yu-2013** [comment]
If using the format of JSON, please try this:

"sort": [["_id", -1]],

The relating API document should be shown in JSON format. This will update.

**Comment by carlduranleau** [comment]
This format is working fine. I just pushed an update in the Hive JS SDK.
