### ISSUE TITLE
Database Delete service returns HTTP204 without the expected payload.

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.Hive.Node#153]
when

DELETE http://localhost:9001/api/v2/vault/db/collection/works?deleteone=false withAuthorization: true payload: {"filter":{"author":"john doe2"}}

is called, hive node returns HTTP 204, when we are expecting is a json with this structure

{ "acknowledged": true, "deleted_count": 1 }

which because of it we have: ERROR HttpException (057x1zw) Unexpected end of JSON input Caused by SyntaxError: SyntaxError: Unexpected end of JSON input

**Comment by fred-yu-2013** [comment]
The API definition of the hive node follows the REST API. So there is no response body returned with HTTP 204.

Please consider this in hive JS SDK.
