### ISSUE TITLE
Database Delete service returns successfully with an invalid collection

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.Hive.Node#154]
The current bug may be linked to the issue https://github.com/elastos/Elastos.Hive.Node/issues/153 which states that the Database Delete service returns HTTP204 without any response payload.

When calling the Delete service with an invalid collection name, we expect to get an HTTP404, but we still get an HTTP204, which is a success status.

**Comment by fred-yu-2013** [comment]
When doing a delete operation, the collection does not exist. Which means the deleting operation is successful. This rule is for all of the hive node APIs.

**Comment by carlduranleau** [comment]
Just tried to reactivate collection deletion tests and they are now working fine. Which means that the Hive Node has been fixed and the delete operation now sends back an HTTP 404 when the collection doesn't exist.
