### ISSUE TITLE
docs/README.md generation procedure not working

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.Hive.Node#194]
Just tried to generate the docs using the [README.md](https://github.com/elastos/Elastos.Hive.Node/blob/master/docs/README.md) procedure and it's not working. It should reviewed to add more information on assumed context and configuration.

The project [README.md](https://github.com/elastos/Elastos.Hive.Node/blob/master/README.md) talks about python 3.6, the docs [README.md](https://github.com/elastos/Elastos.Hive.Node/blob/master/docs/README.md) refers to python 3.8, and I had python 3.10 (Running Ubuntu 22.04 LTS). Even if I had adjusted the assumed python version of the build command, it didn't work.

First, the procedure asks to run `./run.sh test` from the root folder, but even after running `pip install -r requirements.txt` every single test fails with

`E   ModuleNotFoundError: No module named 'flask_cors'`

Here's flask_cors from the requirements.txt installation logs:
```
Collecting flask-cors==3.0.10
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
```

After executing all commands from the docs procedure, here's the result:
```
(.venv) carlduranleau@DevPC:~/git/Elastos.Hive.Node/docs$ PYTHONPATH="${PYTHONPATH}:<HIVE_SOURCE_ROOT>:<HIVE_SOURCE_ROOT>/.venv/lib/python3.10/site-packages" sphinx-build -b html source build
Running Sphinx v4.5.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                             
Exception occurred:
  File "/home/carlduranleau/git/Elastos.Hive.Node/.venv/lib/python3.10/site-packages/sphinxcontrib/autohttp/common.py", line 17, in import_object
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'src'
The full traceback has been saved in /tmp/sphinx-err-qchj1qd9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
(.venv) carlduranleau@DevPC:~/git/Elastos.Hive.Node/docs$
```

I'm working on Javascript projects reaching Hive Node services. I needed the Hive Node API documentation to confirm V1 and V2 available endpoints and payloads to build valid requests. A Python environment isn't required on my side. So the procedure shouldn't assume I have a working Python3 environment ready to run every commands. It needs to provide the needed configuration, and setup information needed to run the procedure correctly.

**Comment by fred-yu-2013** [comment]
1. To use the docs of the hive node, please check this [link](https://apidocs.trinity-tech.io/hive-node-https-apis/).
2. For docs generation, just need to install the requirements and the necessary dependencies in `docs/README.md`. When building, please replace <HIVE_SOURCE_ROOT> with the full path of the hive node root.

**Comment by carlduranleau** [comment]
Thank you for the link, that's exactly what I was searching for. For your second point, that's what I've done, which gave me the result in the ticket.

**Comment by fred-yu-2013** [comment]
Now can you make the docs by the README.md file?
